graph TD
    subgraph "Entorno de Despliegue (e.g., Servidor Linux)"
        subgraph "Docker"
            container("
                <b>Contenedor: facturador-service</b><br/>
                Aplicación Spring Boot<br/>
                Puerto Expuesto: 8080
            ")
        end
    end

    subgraph "Red Externa"
        lb[("Load Balancer / Gateway")]
    end

    lb -- "Tráfico HTTPS:443" --> container